2024-06-12 15:10:59,929 - ERROR - criar_csv - gerarItens - Ocorreu um erro: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Nome da fonte de dados não encontrado e nenhum driver padrão especificado (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2024-06-12 15:13:11,486 - ERROR - criar_csv - gerarItens - Ocorreu um erro: No engine for filetype: 'xl'
2024-06-12 17:30:35,020 - ERROR - criar_csv - gerarItens - Ocorreu um erro: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'PRONIM'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'PRONIM'. (18456)")
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2024-06-12 17:38:41,871 - ERROR - criar_csv - gerarItens - Ocorreu um erro: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'PRONIM'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'PRONIM'. (18456)")
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2024-06-12 17:39:03,270 - ERROR - criar_csv - gerarItens - Ocorreu um erro: (pyodbc.InterfaceError) ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'PRONIM'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'PRONIM'. (18456)")
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2024-06-12 17:45:26,068 - ERROR - criar_csv - gerarItens - Ocorreu um erro: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Nome da fonte de dados não encontrado e nenhum driver padrão especificado (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2024-06-12 17:47:17,432 - ERROR - criar_csv - gerarItens - Ocorreu um erro: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Nome da fonte de dados não encontrado e nenhum driver padrão especificado (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2024-06-12 17:50:40,391 - ERROR - criar_csv - gerarItens - (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Nome da fonte de dados não encontrado e nenhum driver padrão especificado (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2024-06-12 17:52:54,626 - ERROR - criar_csv - gerarItens - (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Nome da fonte de dados não encontrado e nenhum driver padrão especificado (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2024-06-12 17:52:54,627 - ERROR - criar_csv - gerarItens - (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Nome da fonte de dados não encontrado e nenhum driver padrão especificado (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)
2024-06-12 17:54:24,125 - ERROR - criar_csv - gerarItens - (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Nome da fonte de dados não encontrado e nenhum driver padrão especificado (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)
